version: '3.8'

networks:
    local-network:
        driver: bridge

services:
    stjk:
        build:
            context: ./backend
        command: python manage.py run -h 0.0.0.0 -p 80 --with-threads
        ports: 
            - 80:80
        env_file:
            - ./.env
        volumes:
            - ./backend:/usr/src/app
        depends_on:
            - db
        networks: 
            - local-network
    db:
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=stjk
            - POSTGRES_PASSWORD=test
            - POSTGRES_DB=stjk_bytehacks
        networks:
            - local-network

volumes:
    postgres_data:
