version: '3.8'

networks:
    local-network:
        driver: bridge


services:
    stjk:
        build:
            context: ./services/web
        command: python manage.py run -h 0.0.0.0 -p 5000
        expose: 
            - 5000
        env_file:
            - ./.env
        depends_on:
            - users_db
        networks: 
            - local-network
    users_db:
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=stjk
            - POSTGRES_PASSWORD=test
            - POSTGRES_DB=stjk_bytehacks
        networks:
            - local-network
    api:
        build:
            context: ./services/api
        command: python app.py
        expose: 
            - 5000
        env_file: 
            - ./.env
        networks: 
            - local-network
    nginx:
        build: 
            context: ./services/nginx
        ports:
            - 80:80
        depends_on: 
            - stjk
            - api
        networks:
            - local-network
        

volumes:
    postgres_data:
